export enum PeopleFields {
  Title = "title",
  Forename = "forename",
  MiddleNames = "middleNames",
  Surname = "surname",
  Gender = "gender",
  DateOfBirth = "dateOfBirth",
  HomeBuildingName = "homeBuildingName",
  HomeBuildingNumber = "homeBuildingNumber",
  HomeSubBuilding = "homeSubBuilding",
  HomeStreet = "homeStreet",
  HomeCity = "homeCity",
  HomeCounty = "homeCounty",
  HomePostcode = "homePostcode",
  HomePhoneNumber = "homePhoneNumber",
  MobilePhoneNumber = "mobilePhoneNumber",
  EmailAddress = "emailAddress",
}
